version: '3'

services:

  database:
    image: postgres:10
    volumes:
      - database_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database_env
    networks:
      - database_network

  djangoapp:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/djangoapp/src
    networks:
      - database_network
      - nginx_network
    depends_on:
      - database

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx_network
    depends_on:
      - djangoapp

networks:
  database_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  database_volume:
