# Generated by Django 2.2.4 on 2019-08-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('max_amount', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BTC', 'BTC')], max_length=10)),
                ('whitelist_address', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=34)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('rejected', 'Rejected')], max_length=10)),
            ],
        ),
    ]
