# Generated by Django 2.2.4 on 2019-08-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='max_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
