# Generated by Django 2.2.4 on 2019-08-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0003_auto_20190809_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='currency',
            field=models.CharField(choices=[('BTC', 'BTC'), ('USD', 'USD')], max_length=3),
        ),
    ]
